### ISSUE TITLE
No version set

### ISSUE THREAD

**Issue by erland13** [quadram-institute-bioscience/albatradis#12]
In https://github.com/quadram-institute-bioscience/albatradis/blob/master/setup.py version is set incorrectly:
...
version = 'x.y.z'
...

**Comment by andrewjpage** [comment]
Thanks for identifying this. This is a default which should never occur, assuming someone has installed it via a standard mechanism such as 'python setup.py install', 'pip install albatradis', or 'conda install albatradis'. The version is pulled from the file called VERSION on the lines just below version = 'x.y.z'.
