### ISSUE TITLE
Conda installation doesn't provide correct edgeR package

### ISSUE THREAD

**Issue by francesca-short** [quadram-institute-bioscience/albatradis#16]
Having issues with installation using conda. The edgeR/limma package that conda installs isn't correct or does not load properly, so the comparison module fails. Is there a way to update the dependencies that are installed to include a version of edgeR that works? Thanks so much :)

**Comment by sbastkowski** [comment]
Hi francesca-short, sorry for late reply. There is a conflict between the R version you have on your machine which take precedents and the edgeR requirement. Are you using a VM? As with Ubuntu 18.4 it often happens that the preinstalled R version conflicts? The best option is to run it in docker or use a Centos base image in your VM.

**Comment by sbastkowski** [comment]
We also provide R 3.6 installation advice for Ubuntu <19. There we explain how to remove the base version and replace it with 3.6.
