### ISSUE TITLE
Output files - Locus tag

### ISSUE THREAD

**Issue by pmireland** [quadram-institute-bioscience/albatradis#8]
Hi,

Im having the issue with my output files, e.g combined.csv (generated with use_annotation)  The first column of the file contains gene names rather than the locus tag and is therefore identical to column 2. Where no gene name has been allocated for gene in that particular genome the start and end position of the genes are listed in both columns (this can be quite a lot in less well characterised genomes). In the 3rd column it also doesn't seem to be pulling the info from the embl file and just lists "product" for every gene. Im not sure this is my embl file as it outputs correctly when running the biotradis tradis_comparison.R . Thanks for any suggestions you might have.

**Comment by sbastkowski** [comment]
Hi,
thanks for pointing this out. I will look into this and I post an update asap.

**Comment by sbastkowski** [comment]
Hi again,
this issue should be resolved now.
